
services:
  db:
    build: ./db_build
    user: "0:0"
    environment:
      MSSQL_PID: Express
      ACCEPT_EULA: "Y"

    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data
      - db_backups:/var/opt/mssql/backup


    secrets:
      - sa_password
      - db_password
      - db_app_user
      - db_app_password

  app:
    build: .
    depends_on:
      - db
    volumes:
      - certs:/https:ro
    environment:
      - ASPNETCORE_URLS=https://+:7076
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "7076:7076"
    
    secrets:
      - cert_password
      - connection_string
      - sa_password
      - jwt_token_key
      - db_app_user
      - db_app_password
    
secrets:
  sa_password:
    file: secrets/sa_password.txt
  db_password:
    file: secrets/db_password.txt
  db_app_user:
    file: secrets/db_app_user.txt
  db_app_password:
    file: secrets/db_app_password.txt
  cert_password:
    file: secrets/cert_password.txt
  connection_string:
    file: secrets/connection_string.txt
  jwt_token_key:
    file: secrets/jwt_token_key.txt

volumes:
  db_data:
  db_backups:
  certs:
  