#Initial Build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY *.csproj ./
RUN dotnet restore


#Another layer for everything else
COPY . ./
RUN dotnet publish -c Release -o /app/publish


#Runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .


ENTRYPOINT ["dotnet", "DemoApp.dll"]